import './globals.css'
import { Inter } from 'next/font/google'
import Loading from './dashboard/loading'
import Navbar from './components/Navbar'
import { Suspense } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Zulfikri Mirza',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Navbar />
      <Suspense fallback={ <Loading /> }>
        <body className={inter.className}>{children}</body>
      </Suspense>
    </html>
  )
}
